nome = str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {}'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {}, e ele tem {} letras'.format(separa[0],len(separa[0])))
