a = input('Digite algo:')
print('o tipo primitivo é',type(a))
print('só tem espaços?', a.isspace())
print('È um numero?', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('esta em maiusculas?', a.isupper())
print('esta em minusculas?', a.islower())
print('ésta capitalizada?', a.istitle())